-- ============================================================
-- Droomvriendjes.nl - Initial Products Migration
-- Inserts the 10 live products into the Supabase products table
-- Run once against the Supabase PostgreSQL database
-- ============================================================

INSERT INTO products (
    id,
    name,
    short_name,
    price,
    original_price,
    description,
    sku,
    image,
    gallery,
    features,
    benefits,
    badge,
    in_stock,
    stock,
    rating,
    review_count,
    age_range,
    warranty,
    item_id,
    item_category,
    item_category2,
    item_category3,
    item_variant,
    created_at,
    updated_at
) VALUES

-- 1. Slimme Leeuw (AI Serie) - FM666-61
(
    'a1b2c3d4-0001-4000-8000-000000000001',
    'Slimme Leeuw – Nachtlampje met AI Huilsensor & Projector – USB-C Oplaadbaar',
    'Slimme Leeuw',
    49.95,
    59.95,
    'Ontmoet de slimste koning van de nacht. Deze Leeuw is uitgerust met een intelligente AI-huilsensor die direct reageert wanneer je baby onrustig wordt. Dankzij de drie verwisselbare kappen creëer je een magische sterrenhemel, een rustgevende oceaan of een zacht nachtlampje. Met 10 ingebouwde slaapliedjes en 5 witte ruis-geluiden biedt deze leeuw optimale ondersteuning bij het slapen. Volledig oplaadbaar via USB-C, dus geen gedoe met batterijen.',
    'FM666-61',
    '/products/Lion/Lion_Front_product_01.png',
    '["/products/Lion/Lion_Front_product_01.png", "/products/Lion/Lion_Side_product_02.png", "/products/Lion/Lion_back_prodcut_03.png", "/products/Lion/Lion_dimenstions_product_04.png", "/products/Lion/Lion_Macro_prodcut_05.png", "/products/Lion/Lion_gift_product_06.png", "/products/Lion/Sheep_Lifestyle_prodcut_07.png", "/products/Lion/Lion_Lifestyle_prodcut_08.png", "/products/Lion/Lion_Lifestyle_prodcut_09.png", "/products/Lion/Lion_packaging_product_10.png"]',
    '["AI Huilsensor - reageert automatisch op huilen", "3-in-1 Projectie: sterren, oceaan of nachtlampje", "10 slaapliedjes + 5 white noise geluiden", "USB-C oplaadbaar - geen batterijen nodig", "30 minuten auto-uit timer"]',
    '["🤖 AI Huilsensor: Springt automatisch aan om je kindje te troosten", "🌟 3-in-1 Projectie: Kies uit sterren, oceaan of nachtlampje", "🔋 Duurzaam & Oplaadbaar: USB-C kabel inbegrepen", "🎵 10 slaapliedjes en 5 rustgevende geluiden"]',
    'BESTSELLER',
    true,
    100,
    4.9,
    2847,
    'Vanaf 0 maanden',
    '30 dagen slaapgarantie',
    'KNUF_014',
    'Knuffels',
    'AI Slaapknuffels',
    'Slimme Serie',
    'goud-bruin',
    NOW(),
    NOW()
),

-- 2. Slaperig Schaapje (Nodding Off Serie) - FM666-78
(
    'a1b2c3d4-0002-4000-8000-000000000002',
    'Slaperig Schaapje – Interactief Nachtlampje met Projector & 60 Melodieën',
    'Slaperig Schaapje',
    54.95,
    64.95,
    'Dit lieve Schaapje helpt je kindje heerlijk weg te dromen. Dankzij de unieke ''Nodding Off'' functie maakt het schaapje een kalmerende, knikkende beweging die baby''s helpt te ontspannen. Met maar liefst 60 slaapliedjes, 6 witte ruis-geluiden en 7 verschillende lichtmodi is dit het ultieme slaapvriendje.',
    'FM666-78',
    '/products/Sheep/front.png',
    '["/products/Sheep/front.png", "/products/Sheep/side.png", "/products/Sheep/back.png", "/products/Sheep/dim2.png", "/products/Sheep/feature.png", "/products/Sheep/giftable.png", "/products/Sheep/lifestyle1.png", "/products/Sheep/lifestyle2.png", "/products/Sheep/lifestyle3.png", "/products/Sheep/packaging.png"]',
    '["Nodding Off beweging - kalmerende knik-functie", "60 slaapliedjes + 6 white noise geluiden", "7 verschillende lichtmodi", "3 verwisselbare projectiekappen", "Werkt op 3x AA-batterijen"]',
    '["🐑 Dynamische beweging: Kalmerende knik-functie", "🎶 60 melodieën en natuurlijke white noise", "🌈 7 lichtmodi voor perfecte sfeer", "✨ Sterrenhemel en onderwaterwereld projectie"]',
    'POPULAIR',
    true,
    100,
    4.8,
    1923,
    'Vanaf 0 maanden',
    '30 dagen slaapgarantie',
    'KNUF_002',
    'Knuffels',
    'Interactieve Knuffels',
    'Nodding Off Serie',
    'wit-grijs',
    NOW(),
    NOW()
),

-- 3. Slaperige Panda (Nodding Off Serie) - FM666-77
(
    'a1b2c3d4-0003-4000-8000-000000000003',
    'Slaperige Panda – Interactief Nachtlampje met Projector & 60 Melodieën',
    'Slaperige Panda',
    54.95,
    64.95,
    'Onze Slaperige Panda is ontworpen om van bedtijd een feestje te maken. Dit interactieve projector-speelgoed combineert een zachte beweging met een indrukwekkend aanbod aan geluiden en lichteffecten.',
    'FM666-77',
    '/products/Panda/Panda_Front_product_01.png',
    '["/products/Panda/Panda_Front_product_01.png", "/products/Panda/Panda_Side_product_02.png", "/products/Panda/Panda_back_prodcut_03.png", "/products/Panda/Panda_dimenstions_product_04.png", "/products/Panda/Panda_Macro_prodcut_05.png", "/products/Panda/Panda_gift_product_06.png", "/products/Panda/Panda_Lifestyle_prodcut_07.png", "/products/Panda/Panda_Lifestyle_prodcut_08.png", "/products/Panda/Panda_Lifestyle_prodcut_09.png", "/products/Panda/Panda_packaging_product_10.png"]',
    '["Nodding Off beweging - kalmerende knik-functie", "60 slaapliedjes + 6 white noise geluiden", "7 verschillende lichtmodi", "3 verwisselbare projectiekappen", "Werkt op 3x AA-batterijen"]',
    '["🐼 Slaap-ondersteuning: Zachte, rustgevende beweging", "🎵 60 kalmerende liedjes en 6 witte-ruisopties", "🌟 3-in-1 projectie: sterrenhemel, oceaan of nachtlampje", "💡 7 lichtstanden voor perfecte sfeer"]',
    'NIEUW',
    true,
    100,
    4.9,
    1654,
    'Vanaf 0 maanden',
    '30 dagen slaapgarantie',
    'KNUF_003',
    'Knuffels',
    'Interactieve Knuffels',
    'Nodding Off Serie',
    'zwart-wit',
    NOW(),
    NOW()
),

-- 4. Stoere Dinosaurus (Nodding Off Serie) - FM666-82
(
    'a1b2c3d4-0004-4000-8000-000000000004',
    'Stoere Dinosaurus – Interactief Nachtlampje met Projector & 60 Melodieën',
    'Stoere Dino',
    54.95,
    64.95,
    'Voor kleine avonturiers is er deze vriendelijke Dinosaurus. Dit interactieve nachtlampje waakt over de kamer met zijn unieke bewegingen en prachtige lichteffecten.',
    'FM666-82',
    '/products/Dinno/Dinno_Front_product_01.png',
    '["/products/Dinno/Dinno_Front_product_01.png", "/products/Dinno/Dinno_Side_product_02.png", "/products/Dinno/Dinno_back_prodcut_03.png", "/products/Dinno/Dinno_dimenstions_product_04.png", "/products/Dinno/Dinno_Macro_prodcut_05.png", "/products/Dinno/Dinno_gift_product_06.png", "/products/Dinno/Dinno_Lifestyle_prodcut_07.png", "/products/Dinno/Dinno_Lifestyle_prodcut_08.png", "/products/Dinno/Dinno_Lifestyle_prodcut_09.png", "/products/Dinno/Dinno_packaging_product_10.png"]',
    '["Interactieve Nodding Off beweging", "60 slaapliedjes + 6 white noise geluiden", "7 lichtmodi voor avontuurlijke sfeer", "Verwisselbare kappen voor nieuwe ervaringen", "Werkt op 3x AA-batterijen"]',
    '["🦖 Interactief design: Rustgevende beweging", "💡 7 lichtmodi en 60 slaapliedjes", "🌌 Sterrenhemel en oceaanwereld projectie", "🛡️ Geen kind meer bang in het donker"]',
    'FAVORIET',
    true,
    100,
    4.8,
    1432,
    'Vanaf 0 maanden',
    '30 dagen slaapgarantie',
    'KNUF_004',
    'Knuffels',
    'Interactieve Knuffels',
    'Nodding Off Serie',
    'groen',
    NOW(),
    NOW()
),

-- 5. Magische Eenhoorn (Nodding Off Serie) - FM666-74
(
    'a1b2c3d4-0005-4000-8000-000000000005',
    'Magische Eenhoorn – Interactief Nachtlampje met Projector & 60 Melodieën',
    'Magische Eenhoorn',
    54.95,
    64.95,
    'Breng de magie in huis met deze prachtige Eenhoorn. Dit slaapvriendje beweegt zachtjes mee (''Nodding Off'') terwijl het een warme gloed en rustgevende muziek verspreidt.',
    'FM666-74',
    '/products/Unicorn/Unicorn_Front_product_01.png',
    '["/products/Unicorn/Unicorn_Front_product_01.png", "/products/Unicorn/Unicorn_Side_product_02.png", "/products/Unicorn/Unicorn_back_prodcut_03.png", "/products/Unicorn/Unicorn_dimenstions_product_04.png", "/products/Unicorn/Unicorn_Macro_prodcut_05.png", "/products/Unicorn/Unicorn_gift_product_06.png", "/products/Unicorn/Unicorn_Lifestyle_prodcut_07.png", "/products/Unicorn/Unicorn_Lifestyle_prodcut_08.png", "/products/Unicorn/Unicorn_Lifestyle_prodcut_09.png", "/products/Unicorn/Unicorn_packaging_product_10.png"]',
    '["Magische Nodding Off beweging", "60 melodieën + 6 white noise geluiden", "7 lichtmodi voor dromerige sfeer", "3 projectie-thema''s: sterren, oceaan, nachtlamp", "Werkt op 3x AA-batterijen"]',
    '["🦄 Magische sfeer: 7 lichtmodi", "🎶 60 melodieën en 6 witte ruis-opties", "✨ Interactieve beweging voor diepe rust", "💖 Veilig en geborgen gevoel"]',
    'MAGISCH',
    true,
    100,
    4.9,
    2156,
    'Vanaf 0 maanden',
    '30 dagen slaapgarantie',
    'KNUF_005',
    'Knuffels',
    'Interactieve Knuffels',
    'Nodding Off Serie',
    'roze-wit',
    NOW(),
    NOW()
),

-- 6. Bruine Beertje - FM666-72
(
    'a1b2c3d4-0006-4000-8000-000000000006',
    'Bruine Beertje – Nachtlampje met Sterrenprojector & Slaapgeluiden',
    'Bruine Beer',
    49.95,
    59.95,
    'Deze lieve bruine beer is de perfecte slaapvriend voor je kindje. Met een zachte sterrenprojector en rustgevende slaapliedjes creëert dit beertje een geborgen sfeer.',
    'FM666-72',
    '/products/BearBrown/BearBrown_Front_product_01.png',
    '["/products/BearBrown/BearBrown_Front_product_01.png", "/products/BearBrown/BearBrown_Side_product_02.png", "/products/BearBrown/BearBrown_back_prodcut_03.png", "/products/BearBrown/BearBrown_dimenstions_product_04.png", "/products/BearBrown/BearBrown_Macro_prodcut_05.png", "/products/BearBrown/BearBrown_gift_product_06.png", "/products/BearBrown/BearBrown_Lifestyle_prodcut_07.png", "/products/BearBrown/BearBrown_Lifestyle_prodcut_08.png", "/products/BearBrown/BearBrown_Lifestyle_prodcut_09.png", "/products/BearBrown/BearBrown_packaging_product_10.png"]',
    '["Sterrenhemel en oceaanprojectie", "10 rustgevende melodieën", "Zacht diffuus nachtlicht", "30 minuten auto-uit timer", "Werkt op 3x AA-batterijen"]',
    '["🐻 Zachte knuffelpartner", "🌟 Magische sterrenprojectie", "🎵 Rustgevende slaapliedjes", "😴 Helpt bij doorslapen"]',
    'POPULAIR',
    true,
    100,
    4.8,
    1456,
    'Vanaf 0 maanden',
    '30 dagen slaapgarantie',
    'KNUF_007',
    'Knuffels',
    'Slaapknuffels',
    'Beren',
    'bruin',
    NOW(),
    NOW()
),

-- 7. Liggend Schaapje - FM666-79
(
    'a1b2c3d4-0007-4000-8000-000000000007',
    'Liggend Schaapje – Nachtlampje met Sterrenprojectie & Slaapmelodieën',
    'Liggend Schaapje',
    49.95,
    59.95,
    'Dit lieve liggende schaapje is ontworpen om mee te knuffelen terwijl je kindje in slaap valt. Met zachte sterrenprojector en kalmerende melodieën.',
    'FM666-79',
    '/products/SheepTwo/SheepTwo_Front_product_01.png',
    '["/products/SheepTwo/SheepTwo_Front_product_01.png", "/products/SheepTwo/SheepTwo_Side_product_02.png", "/products/SheepTwo/SheepTwo_back_prodcut_03.png", "/products/SheepTwo/SheepTwo_dimenstions_product_04.png", "/products/SheepTwo/SheepTwo_Macro_prodcut_05.png", "/products/SheepTwo/SheepTwo_gift_product_06.png", "/products/SheepTwo/SheepTwo_Lifestyle_prodcut_07.png", "/products/SheepTwo/SheepTwo_Lifestyle_prodcut_08.png", "/products/SheepTwo/SheepTwo_Lifestyle_prodcut_09.png", "/products/SheepTwo/SheepTwo_packaging_product_10.png"]',
    '["Liggend knuffeldesign", "Sterrenhemel projectie", "10 rustgevende melodieën", "Zacht diffuus nachtlicht", "Werkt op 3x AA-batterijen"]',
    '["🐑 Lekker om mee te knuffelen in bed", "🌟 Magische sterrenprojectie", "🎵 Kalmerende slaapliedjes", "😴 Helpt bij inslapen"]',
    'NIEUW',
    true,
    100,
    4.7,
    1234,
    'Vanaf 0 maanden',
    '30 dagen slaapgarantie',
    'KNUF_008',
    'Knuffels',
    'Slaapknuffels',
    'Boerderijdieren',
    'wit-crème',
    NOW(),
    NOW()
),

-- 8. Pinguïn Droomvriendje - FM666-75
(
    'a1b2c3d4-0008-4000-8000-000000000008',
    'Pinguïn Droomvriendje – Nachtlampje met Sterrenprojector & Witte Ruis',
    'Pinguïn',
    49.95,
    59.95,
    'Dit schattige pinguïntje brengt de magie van de poolnacht naar de kinderkamer. Met prachtige sterrenprojectie en rustgevende witte ruis-geluiden.',
    'FM666-75',
    '/products/Penguin/Penguin_Front_product_01.png',
    '["/products/Penguin/Penguin_Front_product_01.png", "/products/Penguin/Penguin_Side_product_02.png", "/products/Penguin/Penguin_back_prodcut_03.png", "/products/Penguin/Penguin_dimenstions_product_04.png", "/products/Penguin/Penguin_Macro_prodcut_05.png", "/products/Penguin/Penguin_gift_product_06.png", "/products/Penguin/Penguin_Lifestyle_prodcut_07.png", "/products/Penguin/Penguin_Lifestyle_prodcut_08.png", "/products/Penguin/Penguin_Lifestyle_prodcut_09.png", "/products/Penguin/Penguin_packaging_product_10.png"]',
    '["Sterrenhemel en oceaanprojectie", "8 white noise geluiden", "Zacht LED nachtlicht", "30 minuten auto-uit timer", "Werkt op 3x AA-batterijen"]',
    '["🐧 Uniek pinguïn design", "⭐ Magische sterrenhemel", "🎶 Kalmerende white noise", "💙 Rustgevende sfeer"]',
    'POPULAIR',
    true,
    100,
    4.8,
    987,
    'Vanaf 0 maanden',
    '30 dagen slaapgarantie',
    'KNUF_009',
    'Knuffels',
    'Slaapknuffels',
    'Pooldieren',
    'blauw-wit',
    NOW(),
    NOW()
),

-- 9. Grijze Teddybeer - FM666-73
(
    'a1b2c3d4-0009-4000-8000-000000000009',
    'Grijze Teddybeer – Premium Nachtlampje met Projector & Melodieën',
    'Grijze Teddy',
    49.95,
    59.95,
    'Deze elegante grijze teddybeer is de perfecte metgezel voor rustige nachten. Met premium sterrenprojectie en kalmerende hartslaggeluiden.',
    'FM666-73',
    '/products/BearTwo/BearTwo_Front_product_01.png',
    '["/products/BearTwo/BearTwo_Front_product_01.png", "/products/BearTwo/BearTwo_Side_product_02.png", "/products/BearTwo/BearTwo_back_prodcut_03.png", "/products/BearTwo/BearTwo_dimenstions_product_04.png", "/products/BearTwo/BearTwo_Macro_prodcut_05.png", "/products/BearTwo/BearTwo_gift_product_06.png", "/products/BearTwo/BearTwo_Lifestyle_prodcut_07.png", "/products/BearTwo/BearTwo_Lifestyle_prodcut_08.png", "/products/BearTwo/BearTwo_Lifestyle_prodcut_09.png", "/products/BearTwo/BearTwo_packaging_product_10.png"]',
    '["Premium sterrenprojectie", "Hartslag en white noise geluiden", "Zacht diffuus nachtlicht", "30 minuten auto-uit timer", "Werkt op 3x AA-batterijen"]',
    '["💤 Helpt sneller inslapen", "🧸 Knuffelbare beste vriend", "🌟 Geruststellend sterrenlicht", "😴 Ondersteunt doorslapen"]',
    'BESTSELLER',
    true,
    100,
    4.9,
    1567,
    'Vanaf 0 maanden',
    '30 dagen slaapgarantie',
    'KNUF_013',
    'Knuffels',
    'Slaapknuffels',
    'Beren',
    'grijs',
    NOW(),
    NOW()
),

-- 10. Droomvriendjes Duo Set - DUO-001
(
    'a1b2c3d4-0010-4000-8000-000000000010',
    'Droomvriendjes Duo Set – Liggend Schaapje & Witte Beer met Projector',
    'Duo Set',
    89.95,
    109.90,
    'De ultieme voordeelset: twee Droomvriendjes voor de prijs van bijna één! Deze set bevat het schattige Liggende Schaapje én de knuffelbare Witte Beer, beide met sterrenprojector en rustgevende melodieën.',
    'DUO-001',
    '/products/DUO/Duo_Front_product_01.png',
    '["/products/DUO/Duo_Front_product_01.png", "/products/DUO/DUO_Side_product_02.png", "/products/DUO/DUO_back_product_03.png", "/products/DUO/Duo_gift1_produc_06.png", "/products/DUO/DUO_gift2_product_06.png", "/products/DUO/Duo_Lifestyle_prodcut_07.png", "/products/DUO/Duo_Lifestyle01_prodcut_08.png", "/products/DUO/Duo_Lifestyle02_prodcut_08.png", "/products/DUO/DUO_Lifestyle_prodcut_09.png"]',
    '["2 complete Droomvriendjes in 1 set", "Liggend Schaapje + Witte Beer", "Beide met sterrenprojectie en melodieën", "€20 voordeelkorting"]',
    '["👫 Perfect voor twee kindjes", "🐑 Schaapje: Heerlijk knuffelbaar liggend design", "🐻 Beer: Zachte witte vacht", "💰 Bespaar €20 op de setprijs"]',
    'VOORDEELSET',
    true,
    100,
    4.9,
    1847,
    'Vanaf 0 maanden',
    '30 dagen slaapgarantie',
    'KNUF_015',
    'Knuffels',
    'Voordeelsets',
    'Duo Sets',
    'wit-crème',
    NOW(),
    NOW()
)

ON CONFLICT (id) DO NOTHING;
